import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/providers/theme'
import { ToastProvider } from '@/providers/toast'
import { ClerkProvider } from "@clerk/nextjs"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mentury',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider enableSystem attribute='class' defaultTheme='dark'>
            <ToastProvider />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
